#!/usr/bin/env python3
import os
import py_compile

def main():
  py_file = os.environ["PYFILE"]
  out_file = py_file + "c"
  py_compile.compile(py_file, cfile=out_file, doraise=True)


if __name__ == "__main__":
  main()
